# imports:
#  - { resource: security.yml }
#  - { resource: services.yml }

parameters:
 locale: en

doctrine:
 dbal:
  charset:  UTF8
  dbname:   %database_name%
  driver:   %database_driver%
  host:  %database_host%
  password: %database_password%
  port:  %database_port%
  user:  %database_user%
  # if using pdo_sqlite as your database driver, add the path in parameters.yml
 orm:
  auto_generate_proxy_classes: %kernel.debug%
  naming_strategy: doctrine.orm.naming_strategy.underscore
  auto_mapping: true

framework:
 assets: ~
 csrf_protection: ~
 default_locale: '%locale'
 #esi:    ~
 form: ~
 fragments: ~
 http_method_override: true
 router:
  resource: '%kernel.root_dir%/config/routing.yml'
  strict_requirements: ~
 secret: %secret%
 # serializer: {enable_annotations: true}
 session:
  handler_id: ~
  save_path: '%kernel.root_dir%/../var/sessions/%kernel.environment%'
 templating: {engines: ['twig']} #assets_version: SomeVersionScheme
 #translator:   {fallback: %locale%}
 trusted_hosts: ~
 trusted_proxies: ~
 validation: {enable_annotations: true}

swiftmailer:
 host:   %mailer_host%
 username:  %mailer_user%
 password:  %mailer_password%
 spool: {type: memory}
 transport: %mailer_transport%

twig:
 debug: %kernel.debug%
 strict_variables: '%kernel.debug%'
