#doctrine:
# orm:
#  metadata_cache_driver: apc
#  result_cache_driver: apc
#  query_cache_driver: apc

#framework:
# serializer:
#  cache: serializer.mapping.cache.apc
# validation:
#  cache: validator.mapping.cache.apc

monolog:
 handlers:
  main:
   action_level: error
   handler: nested
   type: fingers_crossed
  nested:
   level: debug
   path:  %kernel.logs_dir%/%kernel.environment%.log
   type:  stream
  console:
   type: console
