#==Framework
framework:
 test: ~
 session:
  storage_id: session.storage.mock_file
 profiler:
  collect: false

#==Swiftmailer
swiftmailer:
 disable_delivery: true

#==Web Profiles
web_profiler:
 toolbar: false
 intercept_redirects: false
