# imports:
#  - { resource: security.yml }
#  - { resource: services.yml }

#==Framework
framework:
 csrf_protection: ~
 default_locale: '%locale'
 #esi:    ~
 form: ~
 fragments: ~
 http_method_override: true
 router:
  resource: '%kernel.root_dir%/config/routing.yml'
  strict_requirements: ~
 secret:    %secret%
 #translator:   {fallback: %locale%}
 validation:   {enable_annotations: true}
 templating:   {engines: ['twig']} #assets_version: SomeVersionScheme
 trusted_proxies: ~
 session: ~

#==Assetic
assetic:
 bundles: []
 debug: %kernel.debug%
 use_controller: false
 # java: /usr/bin/java
 filters:
  cssrewrite: ~

#==Doctrine
doctrine:
 dbal:
  charset:  UTF8
  dbname:   %database_name%
  driver:   %database_driver%
  host:  %database_host%
  password: %database_password%
  port:  %database_port%
  user:  %database_user%
  # if using pdo_sqlite as your database driver, add the path in parameters.yml
 orm:
  auto_generate_proxy_classes: %kernel.debug%
  auto_mapping: true

#==Twig
twig:
 debug: %kernel.debug%
 strict_variables: '%kernel.debug%'

#==Swiftmailer
swiftmailer:
 host:   %mailer_host%
 username:  %mailer_user%
 password:  %mailer_password%
 spool: {type: memory}
 transport: %mailer_transport%
